Fix I/O issues of subset collections with vector members
AIDASoft/podio pull request #463
Opened 2023-07-21 18:45 UTC by tmadlener

BEGINRELEASENOTES
- Make sure to only access vector member buffers of collections of datatypes with `VectorMembers` if they actually exist. This is necessary to make subset collections of such datatypes work in I/O. Fixes [#462](https://github.com/AIDASoft/podio/issues/462)
- Add a test that reproduces the original issue and is fixed by this.

ENDRELEASENOTES

2023-07-25 11:19 UTC, hegner requested changes
Logic and new tests seem fine to me. Just some nitpicking about formatting and typos. See comments.

2023-07-25 11:19 UTC, hegner commented on python/podio/test_Frame.py
> +    "extension_Contained", "extension_ExternalComponent", "extension_ExternalRelation",
can you fix the indentation / formatting?

2023-07-25 11:19 UTC, hegner commented on tests/read_frame.h
> +  ASSERT(subsetColl.isSubsetCollection(), "subset collection not read back as a sbuset collection");
simple typo in mediate ("sbuset")

2023-07-25 13:40 UTC, tmadlener commented
Now also fixing the second issue reported in https://github.com/AIDASoft/podio/issues/462#issuecomment-1649866017

Unless we want to have that in another PR?

2023-07-26 06:38 UTC, hegner commented on python/podio/test_Frame.py
> +    "extension_Contained", "extension_ExternalComponent", "extension_ExternalRelation",
Sorry, my bad. Seems my phone display was playing me tricks.

2023-07-26 06:38 UTC, merged